AWSTemplateFormatVersion: 2010-09-09
Description: Demo Application Load Balancer

Parameters:
  VpcId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
    Default: /demo/landing-zone/vpc/vpc-id
  PublicSubnet1Id:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /demo/landing-zone/vpc/public-subnet-1-id
  PublicSubnet2Id:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /demo/landing-zone/vpc/public-subnet-2-id
  PublicSubnet3Id:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /demo/landing-zone/vpc/public-subnet-3-id
  HostedZoneId:
    Type: String
    Default: Z10273433NYWURAQVWYW5
  HostedZoneName:
    Type: String
    Default: aws-sandbox.eelviny.me

Mappings:
  RegionMap:
    eu-west-1:
      ElbAccountId: "156460612806"
    eu-central-1:
      ElbAccountId: "054676820928"
    us-east-1:
      ElbAccountId: "127311923021"

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn:
      - LoadBalancerLogsS3BucketPolicy
    Properties:
      Name: demo-application-loadbalancer
      Type: application
      IpAddressType: dualstack
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: "true"
        - Key: access_logs.s3.bucket
          Value: !Ref LoadBalancerLogsS3Bucket
        - Key: access_logs.s3.prefix
          Value: demo-application-loadbalancer
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      SubnetMappings:
        - SubnetId: !Ref PublicSubnet1Id
        - SubnetId: !Ref PublicSubnet2Id
        - SubnetId: !Ref PublicSubnet3Id

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTPS
      Port: 443
      SslPolicy: ELBSecurityPolicy-FS-1-2-Res-2020-10
      Certificates:
        - CertificateArn: !Ref LoadBalancerCertificate
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 200
            MessageBody: Hi there! This is a demo message from your favourite demo load balancer.
            ContentType: text/plain

  LoadBalancerCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub loadbalancer.${HostedZoneName}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub loadbalancer.${HostedZoneName}
          HostedZoneId: !Ref HostedZoneId

  LoadBalancerDnsRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub loadbalancer.${HostedZoneName}
          Type: A
          AliasTarget:
            EvaluateTargetHealth: true
            DNSName: !GetAtt LoadBalancer.DNSName
            HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
        - Name: !Sub loadbalancer.${HostedZoneName}
          Type: AAAA
          AliasTarget:
            EvaluateTargetHealth: true
            DNSName: !GetAtt LoadBalancer.DNSName
            HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: loadbalancer-securitygroup
      GroupDescription: Application Load Balancer security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: Allow inbound web traffic
          FromPort: 443
          ToPort: 443
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: loadbalancer-securitygroup

  LoadBalancerLogsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub demo-loadbalancer-logs-${AWS::AccountId}-${AWS::Region}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      LifecycleConfiguration:
        Rules:
          - Id: RemoveOldLogs
            Status: Enabled
            ExpirationInDays: 30

  LoadBalancerLogsS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoadBalancerLogsS3Bucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Effect: Deny
            Resource: !Sub ${LoadBalancerLogsS3Bucket.Arn}/*
            Principal: "*"
            Condition:
              Bool:
                aws:SecureTransport: false
          - Action: s3:PutObject
            Effect: Allow
            Resource: !Sub ${LoadBalancerLogsS3Bucket.Arn}/demo-application-loadbalancer/AWSLogs/${AWS::AccountId}/*
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !FindInMap [RegionMap, !Ref AWS::Region, ElbAccountId]
                  - :root
